<?php

namespace Database\Seeders;

use App\Models\Meter;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class MetersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $meters = [
            [
                'id_group'      => 1,
                'name'          => 'COUPLING 2 PLTD SEI RAYA',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '252382775',
                'ip_address'    => '10.7.152.25',
                'port'          => 502,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 1,
                'name'          => 'COUPLING 4 PLTD SEI RAYA',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '252382774',
                'ip_address'    => '10.7.152.26',
                'port'          => 502,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 2,
                'name'          => 'COUPLING 2 PLTD SIANTAN',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '252382771',
                'ip_address'    => '10.7.153.94',
                'port'          => 502,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 2,
                'name'          => 'COUPLING 4 PLTD SIANTAN',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '252382770',
                'ip_address'    => '127.0.0.1',
                'port'          => 1003,
                'status'        => 'disconnect',
                'active'        => 'no',
            ],
            [
                'id_group'      => 2,
                'name'          => 'CATEPILAR 78 PLTD SIANTAN',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '252382772',
                'ip_address'    => '10.7.153.104',
                'port'          => 502,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 3,
                'name'          => 'GARDU INDUK 1 PLTD SUKAHARJA',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '253170995',
                'ip_address'    => '10.7.153.253',
                'port'          => 502,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 3,
                'name'          => 'GARDU INDUK 2 PLTD SUKAHARJA',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '253170996',
                'ip_address'    => '10.7.153.251',
                'port'          => 502,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 3,
                'name'          => 'GARDU INDUK 3 PLTD SUKAHARJA',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '253170997',
                'ip_address'    => '10.7.153.249',
                'port'          => 502,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 4,
                'name'          => 'COUPLING 2 PLTD SEI WIE',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '252382778',
                'ip_address'    => '127.0.0.1',
                'port'          => 1009,
                'status'        => 'disconnect',
                'active'        => 'no',
            ],
            [
                'id_group'      => 4,
                'name'          => 'COUPLING 4 PLTD SEI WIE',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '218822610',
                'ip_address'    => '127.0.0.1',
                'port'          => 1010,
                'status'        => 'disconnect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 5,
                'name'          => 'COUPLING 1 PLTD MENYURAI',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '252382777',
                'ip_address'    => '127.0.0.1',
                'port'          => 1011,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
            [
                'id_group'      => 5,
                'name'          => 'COUPLING 3 PLTD MENYURAI',
                'brand'         => 'EDMI',
                'type'          => 'MK6E',
                'ratio_vt'      => '1:1',
                'ratio_ct'      => '1:1',
                'ct_mul'        => 1,
                'vt_mul'        => 1,
                'ct_vt_mul'     => 1,
                'nominal_v'     => '230',
                'nominal_i'     => '5(10)',
                'classes'       => 'Class 0.2',
                'serial_number' => '252382776',
                'ip_address'    => '127.0.0.1',
                'port'          => 1012,
                'status'        => 'connect',
                'active'        => 'yes',
            ],
        ];

        foreach ($meters as $meter) {
            Meter::updateOrCreate(
                ['serial_number' => $meter['serial_number']],
                $meter
            );
        }
    }
}
